defmodule Claudio.A2A.Artifact do
  @moduledoc """
  A2A Artifact — output generated by an agent during task processing.
  """

  alias Claudio.A2A.Part
  import Claudio.A2A.Util, only: [maybe_put: 3]

  @type t :: %__MODULE__{
          artifact_id: String.t(),
          name: String.t() | nil,
          description: String.t() | nil,
          parts: [Part.t()],
          extensions: [String.t()] | nil,
          metadata: map() | nil
        }

  defstruct [:artifact_id, :name, :description, :parts, :extensions, :metadata]

  @doc "Parse an artifact from an API response map."
  @spec from_map(map()) :: t()
  def from_map(map) when is_map(map) do
    %__MODULE__{
      artifact_id: map["artifactId"] || map["artifact_id"],
      name: map["name"],
      description: map["description"],
      parts: parse_parts(map["parts"] || []),
      extensions: map["extensions"],
      metadata: map["metadata"]
    }
  end

  @doc "Convert an artifact to a map for API serialization."
  @spec to_map(t()) :: map()
  def to_map(%__MODULE__{} = artifact) do
    %{
      "artifactId" => artifact.artifact_id,
      "parts" => Enum.map(artifact.parts, &Part.to_map/1)
    }
    |> maybe_put("name", artifact.name)
    |> maybe_put("description", artifact.description)
    |> maybe_put("extensions", artifact.extensions)
    |> maybe_put("metadata", artifact.metadata)
  end

  defp parse_parts(parts) when is_list(parts), do: Enum.map(parts, &Part.from_map/1)
  defp parse_parts(_), do: []
end
